name: build_verify
description: >-
  Test utility to ensure generated Dart code within a package is up-to-date
  when using package:build.
version: 3.1.1
repository: https://github.com/kevmoo/build_verify

environment:
  sdk: ^3.4.0

dependencies:
  io: ^1.0.0
  path: ^1.8.0
  test: ^1.16.6

dev_dependencies:
  build: ^2.0.0
  build_runner: ^2.0.0
  build_version: ^2.0.3
  dart_flutter_team_lints: ^3.0.0
  git: ^2.2.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
