name: build_verify
description: >-
  Test utility to ensure generated Dart code within a package is up-to-date
  when using package:build.
version: 3.1.2-wip
repository: https://github.com/kevmoo/build_verify

environment:
  sdk: ^3.10.0

dependencies:
  io: ^1.0.0
  path: ^1.9.0
  test: ^1.25.9

dev_dependencies:
  build: ^4.0.0
  build_runner: ^2.8.0
  build_version: ^2.1.3
  dart_flutter_team_lints: ^3.0.0
  git: ^2.2.0
  test_descriptor: ^2.0.0
  test_process: ^2.0.0
